services:
  php:
      container_name: php-blog
      user: "1000:1000"
      build:
        context: ./docker/Dockerfiles
        dockerfile: php.Dockerfile
      volumes:
        - .:/var/www/blog
      extra_hosts:
        - "host.docker.internal:host-gateway"
#      environment:
#        PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
#        XDEBUG_MODE: ${XDEBUG_MODE:-off}
#        XDEBUG_CONFIG: "client_host=host.docker.internal"
#        XDEBUG_TRIGGER: 'yes'
  nginx:
    container_name: nginx-blog
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/blog

  mysql:
    container_name: mysql-blog
    image: mysql:8.1
    ports:
      - 3326:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/logs:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  redis:
    container_name: redis-blog
    image: redis:7.4
    ports:
      - "6379:6379"